"""
visualize.py - Plotting script for Digital Twin PID Control System

This script reads the output data from 'simulation_data.csv' (generated by
main.py) and produces a polished, two-panel plot to visualize the 
controller's performance.

The plots generated are:
1.  Tank Level (PV) vs. Setpoint (SP) over time, including settling bands.
2.  Controller Output (Inflow) and Control Error over time.
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# --- Configuration ---
DATA_FILE = 'simulation_data.csv'
OUTPUT_IMAGE = 'pid_response.png'
SETTLING_TOLERANCE = 0.02  # 2% tolerance for settling band


def create_plots(data_file=DATA_FILE, output_image=OUTPUT_IMAGE):
    """
    Reads simulation data from a CSV and generates performance plots.
    
    Args:
        data_file (str): Path to the input CSV file.
        output_image (str): Path to save the output plot image.
    """
    print(f"Attempting to read data from '{data_file}'...")
    
    # --- 1. Load Data ---
    try:
        df = pd.read_csv(data_file)
    except FileNotFoundError:
        print(f"Error: Data file not found at '{data_file}'.")
        print("Please run 'python main.py' first to generate the data.")
        return
    except Exception as e:
        print(f"An error occurred while reading the file: {e}")
        return

    print("Data loaded successfully. Generating plots...")

    # Extract data series
    time = df['time']
    level = df['level']
    setpoint = df['setpoint']
    inflow = df['inflow']
    error = df['error']
    
    sp_value = setpoint.iloc[0] # Get the constant setpoint value

    # --- 2. Create Plots ---
    fig, (ax1, ax2) = plt.subplots(
        nrows=2, 
        ncols=1, 
        figsize=(14, 10), 
        sharex=True
    )
    fig.suptitle('Pure Controls – Digital Twin PID Response', fontsize=18, y=0.96)

    # --- Plot 1: Tank Level (PV) vs. Setpoint (SP) ---
    ax1.plot(time, level, label='Tank Level (PV)', color='blue', linewidth=2)
    ax1.plot(time, setpoint, label=f'Setpoint (SP = {sp_value}%)', color='red', 
             linestyle='--', linewidth=2)
    
    # Add 2% settling bands
    tolerance_band = sp_value * SETTLING_TOLERANCE
    ax1.axhline(y=sp_value + tolerance_band, color='green', 
                linestyle=':', linewidth=1, label='2% Settling Band')
    ax1.axhline(y=sp_value - tolerance_band, color='green', 
                linestyle=':', linewidth=1)
    
    ax1.set_ylabel('Tank Level (%)', fontsize=12)
    ax1.set_title('Process Variable (PV) Response', fontsize=14)
    ax1.legend(loc='lower right')
    ax1.grid(True, which='both', linestyle='--', linewidth=0.5)

    # --- Plot 2: Controller Output (CV) & Error ---
    color_cv = 'tab:purple'
    ax2.plot(time, inflow, label='Inflow (CV)', color=color_cv, linewidth=2)
    ax2.set_xlabel('Time (seconds)', fontsize=12)
    ax2.set_ylabel('Controller Output (%/s)', fontsize=12, color=color_cv)
    ax2.tick_params(axis='y', labelcolor=color_cv)
    ax2.set_title('Controller Output (CV) and Error', fontsize=14)
    ax2.grid(True, which='both', linestyle='--', linewidth=0.5)

    # Create a secondary Y-axis for the error
    ax2_twin = ax2.twinx()
    color_err = 'tab:orange'
    ax2_twin.plot(time, error, label='Error (SP - PV)', color=color_err, 
                  linestyle=':', linewidth=2, alpha=0.8)
    ax2_twin.set_ylabel('Error (%)', fontsize=12, color=color_err)
    ax2_twin.tick_params(axis='y', labelcolor=color_err)
    
    # Add a combined legend for Plot 2
    lines, labels = ax2.get_legend_handles_labels()
    lines2, labels2 = ax2_twin.get_legend_handles_labels()
    ax2_twin.legend(lines + lines2, labels + labels2, loc='lower right')

    plt.tight_layout(rect=[0, 0.03, 1, 0.94]) # Adjust for suptitle
    
    # --- 3. Save Figure ---
    try:
        plt.savefig(output_image)
        print(f"\nPlot saved successfully to '{os.path.abspath(output_image)}'")
    except Exception as e:
        print(f"An error occurred while saving the plot: {e}")
        
    # Optional: Display the plot
    # plt.show()


if __name__ == "__main__":
    # Ensure matplotlib uses a non-interactive backend if run from a script
    # This prevents it from trying to pop up a window on a server
    plt.switch_backend('Agg') 
    create_plots()